#!/bin/bash

if [ $EUID != 0 ]
then
    sudo "$0" "$@"
    exit $?
fi

set -e

exists() {
    command -v $@ >/dev/null 2>&1
}

if exists dnf
then
    echo "Detected DNF package manager"
    dnf upgrade --refresh
elif exists nala
then
    echo "Detected NALA package manager"
    nala full-upgrade
elif exists apt
then
    echo "Detected APT package manager"
    apt update
    apt full-upgrade
else
    echo "Did not detect DNF or APT package manager, cannot upgrade system!"
fi

if exists snap
then
    snap refresh
fi

if exists flatpak
then
    curl --silent https://raw.githubusercontent.com/ivanalejandro0/flatpak-update-checker/a40a7275c36fc2a649738d33897c5d339f787224/flatpak-check-updates.py | python
    flatpak update
fi

